FROM golang:latest

WORKDIR /app/src

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

COPY .env ../.env

COPY temp ../temp

RUN go build -o ../test_app cmd/server/main.go

WORKDIR /app

RUN rm -rf src

EXPOSE 8080

CMD [ "/app/test_app" ]