version: '3.9'
services:
  app:
    container_name: test_app
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - default
  mongodb:
    networks:
      - default
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - 'mongo-data:/data/db'
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok'
      interval: 2s
      timeout: 30s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
networks:
  default:
    driver: bridge
volumes:
  mongo-data: