version: '3.9'
services:
  app:
    container_name: test_app
    environment:
      - MONGO_URL=mongodb://user:password@mongodb:27017/?authSource=admin
      - REDIRECT_URL=http://localhost:8080/user/get_users
      - PORT=8080
      - HOST=localhost
      - DB_NAME=testProject
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - default
  mongodb:
    networks:
      - default
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - 'mongo-data:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
networks:
  default:
    driver: bridge
volumes:
  mongo-data: